from os import truncate
import pandas as pd
import numpy as np
from transformers import pipeline

def get_Bart_result(prompt) -> str:
    """Generate a summary for the given prompt using BART.\n
    
    Keyword arguments:
    prompt -- prompt to be summarized\n
    Return: Summary generated by BART
    """
    
    summarizer = pipeline("summarization")
    result = summarizer(prompt, truncate = True, min_length = 100, do_sample=False)
    
    return result[0]['summary_text']